Add Prodos-compatible clock card.
ct6502/apple2ts pull request #6
Opened 2023-08-17 05:17 UTC by code-bythepound

Implements a prodos compatible clock that works with (almost?) all versions of prodos without needing a special driver.

2023-08-17 19:33 UTC, ct6502 requested changes
Just a few minor nits

2023-08-17 19:33 UTC, ct6502 commented on src/emulator/clock.ts
> +  if (!enable)
should probably have enable=false actually disable the clockcard, but now that I think about it, there isn't a way to remove a "slotDriver". Can do this later

2023-08-17 19:33 UTC, ct6502 commented on src/emulator/clock.ts
> +  let date: Date = new Date()
could probably be a "const", and I don't think you need to specify the type as Date, because TypeScript will automatically figure it out

2023-08-17 19:33 UTC, ct6502 commented on src/emulator/clock.ts
> +  let output: string = zeroPad(date.getMonth() + 1, 2)  + ','
don't need to specify type String - TS should know this

2023-08-17 19:33 UTC, ct6502 commented on src/emulator/motherboard.ts
> +  enableClockCard(true,2)
Since "enable" and "slot" both have defaults, we technically don't need to pass in any arguments, so it could be just "enableClockCard()"

2023-08-18 02:13 UTC, code-bythepound commented on src/emulator/clock.ts
> +  if (!enable)
Ok.

2023-08-19 04:01 UTC, ct6502 approved these changes

2023-08-19 04:03 UTC, merged

2023-08-19 04:03 UTC, ct6502 commented
Thanks! All merged.