Add methods to control slot IO
ct6502/apple2ts pull request #8
Opened 2023-08-17 05:40 UTC by code-bythepound

This allows a slot driver to register a callback for slot IO.

2023-08-18 05:28 UTC, ct6502 requested changes
Overall this looks great! Just a few potential changes. Thanks!

2023-08-18 05:28 UTC, ct6502 commented on src/emulator/memory.ts
> +const slotIOJumpTable = new Array<(a:number, value: number, isRead:boolean) => number>(8)
I think I've been using the convention "isWrite" for the flag, instead of "isRead". Can we switch the meaning?

2023-08-18 05:28 UTC, ct6502 commented on src/emulator/memory.ts
> +const checkSlotIO = (addr : number): any => {
Rather than returning the function, maybe we should just pass in the address and "isWrite" flag, and just call the function if it exists. That way we only have to return a number giving the memory value.

2023-08-18 05:28 UTC, ct6502 commented on src/emulator/memory.ts
> +export const setSlotIODriver = (slot: number, fn: (a:number, v: number, isRead:boolean) => number) => {
isRead -> isWrite (and flip meaning)

2023-08-18 05:28 UTC, ct6502 commented on src/emulator/memory.ts
> +  const func = checkSlotIO(addr)
just call the function inside checkSlotIO and return a number

2023-08-18 05:28 UTC, ct6502 commented on src/emulator/memory.ts
> +    const func = checkSlotIO(addr)
just call the func within checkSlotIO

2023-08-18 05:28 UTC, ct6502 commented on src/emulator/memory.ts
> +      // do i need to call updateAddressTables() here?
that is an excellent question - I can see scenarios where the peripheral card might mess with the soft switches. Maybe the code could look something like:
if (addr >= 0xC090) {
  checkSlotIO(...)
} else {
  checkSoftSwitches(...)
}
if (addr <= 0xC00F || addr >= 0xC050) {
   updateAddressTables()
}

2023-08-18 05:28 UTC, ct6502 commented on src/emulator/memory.ts
>    if (addr >= SWITCHES.DRVSM0.offAddr && addr <= SWITCHES.DRVWRITE.onAddr) {
could we convert the slot 6 disk drive into a fancy checkSlotIO? That would be very cool!

2023-08-19 01:45 UTC, code-bythepound commented on src/emulator/memory.ts
>    if (addr >= SWITCHES.DRVSM0.offAddr && addr <= SWITCHES.DRVWRITE.onAddr) {
Sure.  Can I do that in a follow-up change?

2023-08-19 01:54 UTC, ct6502 commented on src/emulator/memory.ts
>    if (addr >= SWITCHES.DRVSM0.offAddr && addr <= SWITCHES.DRVWRITE.onAddr) {
Absolutely!

2023-08-20 03:45 UTC, ct6502 approved these changes

2023-08-20 03:46 UTC, merged