Pass mouse events from canvas main to worker
ct6502/apple2ts pull request #9
Opened 2023-08-17 06:07 UTC by code-bythepound

Pass mouse move and button press events from canvas to the worker for later use.

2023-08-18 05:35 UTC, ct6502 requested changes
Looks really good, just a minor suggestion.

2023-08-18 05:35 UTC, ct6502 commented on src/canvas.tsx
> +    passMouseEvent({x:-1, y:-1, buttons:event.which === 1 ? 0x10 : 0x11});
on MouseDown/Up, should we still compute the x/y and return them? I can see someone being interested.

2023-08-18 05:35 UTC, ct6502 commented on src/emulator/utility.ts
> +export type MouseEventSimple = {
I like this - very simple! 👍

2023-08-19 01:42 UTC, code-bythepound commented on src/emulator/utility.ts
> +export type MouseEventSimple = {
Thanks.  What does the react error message mean, and how do I fix it?

2023-08-19 02:01 UTC, ct6502 commented on src/emulator/utility.ts
> +export type MouseEventSimple = {
Ugh, that's a really tricky error message, and one that I've struggled with many times. Here's an article which sort of explains it: https://kinsta.com/knowledgebase/react-hook-useeffect-has-a-missing-dependency/#:~:text=The%20dependency%20array%20is%20the,the%20effect%20is%20re%2Dexecuted.
I think the short answer is that you have to put the handleMouseDown, handleMouseMove, and handleMouseUp into the "dependency" array at the end of the useEffects method. But there's always complexity and confusion whenever I do it.
Are you using VS Code to write your code? If so, then it should warn you about missing dependencies. Otherwise, you'll probably need to run "npm run build" at the command line to see those errors.
If it doesn't seem to be working, just finish up the other changes, and we can merge the code and I'll take a crack at fixing it.

2023-08-20 07:05 UTC, code-bythepound commented on src/emulator/utility.ts
> +export type MouseEventSimple = {
I think this fixed the errors, by moving the methods inside useEffect.

2023-08-21 02:48 UTC, merged